# fly.toml app configuration file generated for shy-haze-6229 on 2023-09-11T14:23:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-haze-6229"
primary_region = "yul"
console_command = "/code/WebAppTeam4/manage.py shell"

[build]

[deploy]
  release_command = "python /code/WebAppTeam4/manage.py migrate"

[env]
  PORT = "8000"
SECRET_KEY="django-insecure-4u10lnpkw-h(xg@u7k+g2(-7%)19=54ee@(z)7qlsj&hl^-&xa"
EMAIL_HOST_USER="email-robot@meta.ua"
EMAIL_HOST_PASSWORD="Robot_159357!"
EMAIL_HOST="smtp.meta.ua"
EMAIL_PORT="465"
DATABASE_NAME="Dj_proj_team4"
DATABASE_USER="postgres"
DATABASE_PASSWORD="567234"
DATABASE_HOST="195.201.150.230"
DATABASE_PORT="5433"
DROP_BOX="sl.Blxyn0tJT8FXBjfMOpH7J1JOt4tIgQ612cmCgaL2m9OlEpJtNEXpebTJmvDZ9fw9Rco82M1lSionPkjOPHCMEwbwO2jACH4kbdhknW1fLkLQhnxf1OzwRQ97Pffwg_I0K0XPDc1hmdvj"
REDIS="redis"
REDIS_HOST="195.201.150.230"
REDIS_PASSWORD="567234"
REDIS_PORT="6379"
REDIS_DB="db0"
WEATHER_API_KEY="3478743f8ff6ad5d9cae9ea84b3cb414"
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
