# Generated by Django 4.2.4 on 2023-09-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
    ]
