# Generated by Django 4.2.4 on 2023-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0004_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=30000),
        ),
    ]
