# Generated by Django 4.2.4 on 2023-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0006_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='orig_name',
            field=models.CharField(default='file', max_length=255),
            preserve_default=False,
        ),
    ]
