# Generated by Django 4.2.4 on 2023-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0002_rename_name_contact_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
