# Generated by Django 4.2.4 on 2023-09-03 15:46

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('path', models.FileField(upload_to=files.models.update_filename)),
                ('category', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
